panitsa/urls.py
from django.urls import path
from django.contrib.auth.views import *
from django.contrib.auth.decorators import *
from .views import *
from . import *


urlpatterns = [
    
    
    path('', home, name='home'),
    path('login_user/',login_user , name='login_user'),
    path('signup/', signup, name='signup'),
    path('logout_user/', logout_user, name='logout_user'),
    path('representative/', representative, name='representative'),
    path('activity_news/', activity_news, name='activity_news'),
    path('Income_expenses/', income_expenses, name='income_expenses'),
    
    path('admin/login/', LoginView.as_view(), name='admin_login'),
    path('admin/logout/', LogoutView.as_view(), name='admin_logout'),
    
    path('admin/admin_edit/', admin_edit, name='admin_edit'),
    
    path('admin/admin_edit/add_representative/', add_representative, name='add_representative'),
    path('admin/admin_representatives/', admin_representatives, name='admin_representatives'),
    path('admin/edit_representative/<int:representative_id>/', edit_representative, name='edit_representative'),
    path('admin/delete_representative/<int:representative_id>/', delete_representative, name='delete_representative'),
    
    path('admin/admin_edit/add_villagepublic/', add_villagepublic, name='add_villagepublic'),
    path('admin/admin_villagepublic/', admin_villagepublic, name='admin_villagepublic'),
    path('admin/edit_villagepublic/<int:villagepublic_id>/', edit_villagepublic, name='edit_villagepublic'),
    path('admin/delete_villagepublic/<int:villagepublic_id>/', delete_villagepublic, name='delete_villagepublic'),
    
    path('admin/admin_edit/add_activity_news/', add_activity_news, name='add_activity_news'), 
    path('admin/admin_activity_news/', admin_activity_news, name='admin_activity_news'),
    path('admin/edit_activity_news/<int:activity_news_id>/', edit_activity_news, name='edit_activity_news'),
    path('admin/delete_activity_news/<int:activity_news_id>/', delete_activity_news, name='delete_activity_news'),
    
    path('admin/admin_edit/add_income_expenses/', add_income_expenses, name='add_income_expenses'),
    path('admin/admin_income_expenses/', admin_income_expenses, name='admin_income_expenses'),
    path('admin/edit_income_expenses/<int:income_expenses_id>/', edit_income_expenses, name='edit_income_expenses'),
    path('admin/delete_income_expenses/<int:income_expenses_id>/', delete_income_expenses, name='delete_income_expenses'),
    
    path('chat_report/', chat_report, name='chat_report'),
    path('admin/user_list/', admin_user_list, name='admin_user_list'),
    path('admin/admin_edit/admin_road_chat/<int:user_id>/', admin_road_chat, name='admin_road_chat'),
    path('admin/admin_edit/admin_water_chat/<int:user_id>/', admin_water_chat, name='admin_water_chat'),
    path('admin/admin_edit/admin_electricity_chat/<int:user_id>/', admin_electricity_chat, name='admin_electricity_chat'),
    path('admin/admin_edit/admin_general_chat/<int:user_id>/', admin_general_chat, name='admin_general_chat'),
    
    path('road_chat/', road_chat, name='road_chat'), 
    path('water_chat/', water_chat, name='water_chat'),
    path('electricity_chat/', electricity_chat, name='electricity_chat'),
    path('general_chat/', general_chat, name='general_chat'),

    
    path('donation/', donation_form, name='donation_form'),
    path('admin_dashboard/', admin_dashboard, name='admin_dashboard'),
    path('approve_donation/<int:donation_id>/', approve_donation, name='approve_donation'),
    path('donation/<int:donation_id>/generate_pdf/', generate_donation_pdf, name='generate_donation_pdf'),
    path('thank_you/<int:donation_id>/', thank_you_page, name='thank_you_page'),
    path('admin/reject_donation/<int:donation_id>/', reject_donation, name='reject_donation'),
    path('admin/monthly_summary/', admin_monthly_summary, name='admin_monthly_summary'),
    path('monthly_summary/', user_monthly_summary, name='user_monthly_summary'),
    
]

projectWeb/urls.py
# urls.py in your project


#from django.contrib import admin
from django.urls import path, include
from projectWeb.admin import CustomLoginView, EditView
from panitsa.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('panitsa.urls')),
    path('admin_login/', CustomLoginView.as_view(), name='admin_login'),
    path('admin/admin_edit/',EditView.as_view(), name='admin_edit'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panitsa/models.py
#models.py
from django.db import models
from django.contrib.auth.models import *
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from .models import *


User = get_user_model()


class Representative(models.Model):
    image = models.ImageField(upload_to='Representative_images/')
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10)
    
    class Meta:
        db_table = 'representative'
        
class Activity_news(models.Model):
    image = models.ImageField(upload_to='images/')
    text = models.TextField()
    time = models.TimeField()
    date = models.DateField()
    
    class Meta:
        db_table = 'activity_news'
        
class Villagepublic(models.Model):
    image = models.ImageField(upload_to='Villagepublic_images/')
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10)

    class Meta:
        db_table = 'villagepublic'
        
class Income_expenses(models.Model):
    date = models.DateField()
    time = models.TimeField()
    income = models.TextField()
    income_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    expenses = models.TextField()
    expenses_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    image = models.ImageField(upload_to='Income_expenses_images/')
        
    class Meta:
        db_table = 'income_expenses'

class ChatMessage(models.Model):
    CATEGORY_CHOICES = [
        ('road', 'เรื่องถนน'),
        ('water', 'เรื่องน้ำ'),
        ('electricity', 'เรื่องไฟฟ้า'),
        ('general', 'เรื่องทั่วไป'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    admin_message = models.BooleanField(default=False)
    image = models.ImageField(upload_to='chat_images/', blank=True, null=True)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)                           
    class Meta:
        db_table = 'chat_message'



class Donation(models.Model):
    PAYMENT_METHOD_CHOICES = [
        ('transfer', 'เงินโอน'),
    ]

    payment_method = models.CharField(max_length=10, choices=PAYMENT_METHOD_CHOICES)
    date = models.DateField()
    subject = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=10)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    amount_text = models.CharField(max_length=255)
    transfer_receipt = models.ImageField(upload_to='receipts/', null=True, blank=True)
    approved = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)

    class Meta:
        db_table = 'Donation'

panitsa/forms.py
#forms.py
from django import forms
from django.contrib.auth.forms import *
from django.core.exceptions import *
from django.utils.translation import gettext_lazy as _
from django.utils.translation import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *


class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        

class RepresentativeForm(forms.ModelForm):
    class Meta:
        model = Representative
        fields = ['image', 'first_name', 'last_name', 'position', 'phone_number']

class Activity_newsForm(forms.ModelForm):
    class Meta:
        model = Activity_news
        fields = ['text', 'date', 'time', 'image']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
        }
    
class VillagepublicForm(forms.ModelForm):
    class Meta:
        model = Villagepublic
        fields = ['image', 'first_name', 'last_name', 'position', 'phone_number']



class Income_expensesForm(forms.ModelForm):
    class Meta:
        model = Income_expenses
        fields = ['date', 'time', 'income', 'income_amount', 'expenses', 'expenses_amount', 'image']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
            'income_amount': forms.NumberInput(attrs={'step': '0.01'}),
            'expenses_amount': forms.NumberInput(attrs={'step': '0.01'}),
        }


class MessageForm(forms.ModelForm):
    class Meta:
        model = ChatMessage
        fields = [ 'message', 'image']
        widgets = {
            'message': forms.Textarea(attrs={'rows': 2, 'placeholder': 'พิมพ์ข้อความตอบกลับที่นี่...'}),
            
        }


class DonationForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = [
            'payment_method', 'date', 'subject', 'name', 'address', 
            'phone', 'amount', 'amount_text', 'transfer_receipt'
        ]
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'payment_method': forms.RadioSelect(choices=Donation.PAYMENT_METHOD_CHOICES),
        }

panitsa/templates/panitsa/activity_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ข่าวสารและกิจกรรม</title>
    <style>
        body {
            text-align: center;
            background-color: #f7f7f7; 
            padding: 30px; 
            font-family: 'Arial', sans-serif; 
        }
        h1 {
            color: #333;
        }
        .news-container {
            display: flex; 
            align-items: center; 
            justify-content: center; 
            flex-wrap: wrap;
        }
        .news-item {
            margin: 10px;
            padding: 20px; 
            background-color: #fff; 
            border-radius: 8px; 
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); 
            text-align: left; 
            max-width: 300px; 
        }
        img {
            max-width: 40%;
            margin-bottom: 10px;
            height: auto; 
            border-radius: 4px; 
        }
        p { 
            font-size: 18px; 
            line-height: 1.4; 
        }
        @media screen and (max-width: 600px) 
    </style>

</head>
<a href="{% url 'home' %}" class="action-links">หน้าแรก</a>
<body>
    <h1>ข่าวสารกิจกรรม</h1>
    {% for activity_news in activity_news %}
    <div>
        <img src="{{ activity_news.image.url }}" alt="{{ activity_news.text }}">
        {% if activity_news.image1 %}
            <img src="{{ activity_news.image1.url }}" alt="{{ activity_news.text }}">
        {% endif %}
        <p>{{ activity_news.text }}</p>
        <p>วันที่: {{ activity_news.date|date:"j/n/Y" }} | เวลา: {{ activity_news.time|time:"G:i" }}</p>
    </div>
{% endfor %}
</body>
</html>

panitsa/templates/panitsa/chat_report.html
<!-- chat_report.html -->
<!DOCTYPE html>
<html>
<head>
    <title>เลือกประเภทเรื่อง</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            text-align: center;
            background-size: cover;
            background-position: center;
            height: 100vh;
            
        }

        h1 {
            color: #333;
            background-color: white;
            padding: 20px;
            font-size: 24px;
        }

        .button-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            margin-top: 100px;
        }

        .button {
            margin: 10px;
            padding: 15px 30px;
            background-color: #cc33ff;
            color: #FFF;
            border: none;
            border-radius: 5px;
            text-decoration: none;
            font-size: 18px;
            cursor: pointer;
        }

        @media screen and (max-width: 600px) {
            h1 {
                font-size: 18px;
            }

            .button {
                padding: 10px 20px;
                font-size: 14px;
            }
        }
    </style>
</head>
<body>
    <a href="{% url 'home' %}" class="action-links">หน้าแรก</a>
    <div class="button-container">
        <form method="post" action="{% url 'chat_report' %}">
            {% csrf_token %}
            <button type="submit" name="category" value="road" class="button">เรื่องถนน</button>
            <button type="submit" name="category" value="water" class="button">เรื่องน้ำ</button>
            <button type="submit" name="category" value="electricity" class="button">เรื่องไฟฟ้า</button>
            <button type="submit" name="category" value="general" class="button">เรื่องทั่วไป</button>
        </form>
    </div>
</body>
</html>

panitsa/templates/panitsa/donation_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Donation Form</title>
    
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const paymentMethodSelect = document.querySelector('#id_payment_method');
            const transferReceiptField = document.querySelector('#transfer_receipt_field');
            const bankDetails = document.getElementById('bank_details');
            const form = document.querySelector('form');
            const errorMessage = document.getElementById('error_message');

            function updateFormFields() {
                const selectedMethod = paymentMethodSelect.value;
                if (selectedMethod === 'transfer') {
                    transferReceiptField.style.display = 'block';
                    bankDetails.style.display = 'block';
                } else {
                    transferReceiptField.style.display = 'none';
                    bankDetails.style.display = 'none';
                }
            }

            paymentMethodSelect.addEventListener('change', updateFormFields);

            // Initial update on page load
            updateFormFields();

            const copyButton = document.getElementById('copy_button');
            copyButton.addEventListener('click', function () {
                const accountNumber = document.getElementById('account_number').innerText;
                navigator.clipboard.writeText(accountNumber).then(function () {
                    alert('คัดลอกเลขบัญชีเรียบร้อยแล้ว');
                }, function () {
                    alert('ไม่สามารถคัดลอกเลขบัญชีได้');
                });
            });

            form.addEventListener('submit', function (event) {
                const selectedMethod = paymentMethodSelect.value;
                if (selectedMethod !== 'transfer') {
                    event.preventDefault(); 
                    errorMessage.textContent = 'กรุณาเลือกเป็น เงินโอน';
                } else {
                    errorMessage.textContent = ''; 
                }
            });
        });
    </script>
</head>
<body>
    <a href="{% url 'home' %}" class="action-links">หน้าแรก</a>
    <div class="form-container">
        <h2>แบบฟอร์มการบริจาค</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-section">
                <label for="id_payment_method">Payment method:</label><br>
                <select id="id_payment_method" name="payment_method">
                    {% for choice in form.payment_method.field.choices %}
                        <option value="{{ choice.0 }}" {% if form.payment_method.value == choice.0 %}selected{% endif %}>
                            {{ choice.1 }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            
            <div class="form-section">
                <label for="id_date">วันที่:</label><br>
                {{ form.date }}
            </div>
            
            <div class="form-section">
                <label for="id_subject">เรื่อง:</label><br>
                {{ form.subject }}
            </div>
            
            <div class="form-section">
                <label for="id_name">ชื่อ-นามสกุล:</label><br>
                {{ form.name }}
            </div>
            
            <div class="form-section">
                <label for="id_address">ที่อยู่:</label><br>
                {{ form.address }}
            </div>
            
            <div class="form-section">
                <label for="id_phone">เบอร์โทร:</label><br>
                {{ form.phone }}
            </div>
            
            <div class="form-section">
                <label for="id_amount">จำนวนเงิน (ตัวเลข):</label><br>
                {{ form.amount }}
            </div>
            
            <div class="form-section">
                <label for="id_amount_text">จำนวนเงิน (ตัวอักษร):</label><br>
                {{ form.amount_text }}
            </div>
            
            
            
            <div id="transfer_receipt_field" class="form-section" style="display: none;">
                <label for="id_transfer_receipt">Transfer receipt:</label><br>
                {{ form.transfer_receipt }}
            </div>
            
            <div id="bank_details" class="form-section" style="display: none;">
                <p>ชื่อธนาคาร: ธนาคารกรุงไทย</p>
                <p>ชื่อที่ต้องโอน: บ้านสร้างเม็ก</p>
                <p>เลขบัญชี: <span id="account_number">123-456-7890</span> <button type="button" id="copy_button">คัดลอก</button></p>
            </div>
            
            <div class="form-section">
                <button type="submit">ส่งข้อมูล</button>
                <p id="error_message" class="error-message"></p>
            </div>
        </form>
    </div>
</body>
</html>

panitsa/templates/panitsa/electricity_chat.html
<!DOCTYPE html>
<html>
<head>
    <title>แชทเรื่องไฟฟ้า</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
        }
        .action-links {
            display: block;
            text-align: center;
            margin-bottom: 20px;
            text-decoration: none;
            color: #007bff;
        }
        .chat-container {
            margin-bottom: 80px;
        }
        .message {
            clear: both;
            margin-bottom: 10px;
            padding: 10px;
            border-radius: 5px;
            max-width: 60%;
            position: relative;
            word-wrap: break-word;
        }
        .user-message {
            background-color: #f9f9f9;
            text-align: right;
            float: right;
        }
        .admin-message {
            background-color: #e1f5fe;
            text-align: left;
            float: left;
        }
        .message-content {
            padding-bottom: 10px;
        }
        .user-message img {
            max-width: 50%;
            float: right;
            display: block;
            margin-top: 10px;
        }
        .admin-message img {
            max-width: 50%;
            float: left;
            display: block;
            margin-top: 10px;
        }
        .message small {
            display: block;
            font-size: 10px;
            color: #888;
            text-align: right;
            margin-top: 5px;
        }
        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }
        .form-container {
            position: fixed;
            bottom: 0;
            width: 100%;
            padding: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
    <a href="{% url 'chat_report' %}" class="action-links">เลือกประเภทเรื่อง</a>
    <div class="chat-container">
        <h1>เรื่องไฟฟ้า</h1>
        {% if messages %}
            {% for message in messages %}
                <div class="message {% if message.admin_message %}admin-message{% else %}user-message{% endif %} clearfix">
                    <div class="message-content">
                        {{ message.message }}
                        {% if message.image %}
                            <br><img src="{{ message.image.url }}" alt="Uploaded Image">
                        {% endif %}
                    </div>
                    <small>{{ message.timestamp }}</small>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="form-container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" name="category" value="electricity" class="button">ส่ง</button>
        </form>
    </div>
</body>
</html>

panitsa/templates/panitsa/general_chat.html
<!DOCTYPE html>
<html>
<head>
    <title>แชทเรื่องทั่วไป</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
        }
        .action-links {
            display: block;
            text-align: center;
            margin-bottom: 20px;
            text-decoration: none;
            color: #007bff;
        }
        .chat-container {
            margin-bottom: 80px;
        }
        .message {
            clear: both;
            margin-bottom: 10px;
            padding: 10px;
            border-radius: 5px;
            max-width: 60%;
            position: relative;
            word-wrap: break-word;
        }
        .user-message {
            background-color: #f9f9f9;
            text-align: right;
            float: right;
        }
        .admin-message {
            background-color: #e1f5fe;
            text-align: left;
            float: left;
        }
        .message-content {
            padding-bottom: 10px;
        }
        .user-message img {
            max-width: 50%;
            float: right;
            display: block;
            margin-top: 10px;
        }
        .admin-message img {
            max-width: 50%;
            float: left;
            display: block;
            margin-top: 10px;
        }
        .message small {
            display: block;
            font-size: 10px;
            color: #888;
            text-align: right;
            margin-top: 5px;
        }
        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }
        .form-container {
            position: fixed;
            bottom: 0;
            width: 100%;
            padding: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
    <a href="{% url 'chat_report' %}" class="action-links">เลือกประเภทเรื่อง</a>
    <div class="chat-container">
        <h1>เรื่องทั่วไป</h1>
        {% if messages %}
            {% for message in messages %}
                <div class="message {% if message.admin_message %}admin-message{% else %}user-message{% endif %} clearfix">
                    <div class="message-content">
                        {{ message.message }}
                        {% if message.image %}
                            <br><img src="{{ message.image.url }}" alt="Uploaded Image">
                        {% endif %}
                    </div>
                    <small>{{ message.timestamp }}</small>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div class="form-container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" name="category" value="general" class="button">ส่ง</button>
        </form>
    </div>
</body>
</html>

panitsa/templates/panitsa/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>หน้าแรก</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            text-align: center;
            background-image: url('https://kiji.life/newkiji/wp-content/uploads/2019/12/japan-edo-village-sanmachisuji-takayama-japan.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            font-family: Arial, sans-serif;
        }
        
        h1 {
            color: #333;
            background-color: rgba(255, 255, 255, 0.9);
            padding: 20px;
            font-size: 24px;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        
        .button-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            margin-top: 20px;
        }
        
        .button {
            margin: 10px;
            padding: 15px 30px;
            background-color: #0074D9;
            color: #FFF;
            border: none;
            border-radius: 5px;
            text-decoration: none;
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.3s ease, box-shadow 0.3s ease;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        
        .button:hover {
            background-color: #0056b3;
            box-shadow: 0 6px 8px rgba(0, 0, 0, 0.2);
        }
        
        @media screen and (max-width: 600px) {
            h1 {
                font-size: 18px;
            }
        
            .button {
                padding: 10px 20px;
                font-size: 14px;
            }
        }

        .logout {
            position: absolute;
            top: 10px;
            right: 10px;
            color: #FFF;
            text-decoration: none;
            font-size: 18px;
            padding: 10px 20px;
            background-color: #FF4136;
            border-radius: 5px;
            transition: background-color 0.3s ease, box-shadow 0.3s ease;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .logout:hover {
            background-color: #CC342B;
            box-shadow: 0 6px 8px rgba(0, 0, 0, 0.2);
        }
    </style>
</head>
<body>
    <a href="{% url 'logout_user' %}" class="logout">Logout</a>
    <div style="margin-top: 120px;">
        <h1>ยินดีต้อนรับบ้านสร้างเม็ก</h1>
    </div>
    <div class="button-container">
        <a href="{% url 'representative' %}" class="button">สมาชิกผู้แทนในหมู่บ้าน</a>
        <a href="{% url 'activity_news' %}" class="button">ข่าวสารกิจกรรม</a>
        <a href="{% url 'income_expenses' %}" class="button">รายรับรายจ่าย</a>
        <a href="{% url 'donation_form' %}" class="button">แบบฟอร์มการรับเงินบริจาค</a>
        <a href="{% url 'chat_report' %}" class="button">แชทแจ้งความเดือดร้อน</a>
        <a href="{% url 'user_monthly_summary' %}" class="button">รายงานรายรับรายจ่าย</a>
    </div>
</body>
</html>

panitsa/templates/panitsa/login_user.html
<!-- login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<style>
    body {
        margin: 0;
        padding: 0;
        text-align: center;
        background-image: url('https://kiji.life/newkiji/wp-content/uploads/2019/12/japan-edo-village-sanmachisuji-takayama-japan.jpg');
        background-size: cover;
        background-position: center;
        height: 100vh;
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;    
        display: flex;
        align-items: center;
        justify-content: center; 
    }
    form {
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        width: 300px;
    }

    label {
        display: block;
        margin-bottom: 8px;
    }

    input {
        width: 100%;
        padding: 8px;
        margin-bottom: 12px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button {
        background-color: #4caf50;
        color: #fff;
        padding: 10px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
    }
</style>
<body>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
        <p>ยังไม่มีบัญชีใช่ไหม? <a href="{% url 'signup' %}">สมัครสมาชิก</a></p>
    </form>
</body>
</html>

panitsa/templates/panitsa/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>สมัครสมาชิก</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            text-align: center;
            background-image: url('https://kiji.life/newkiji/wp-content/uploads/2019/12/japan-edo-village-sanmachisuji-takayama-japan.jpg');
            background-size: cover;
            background-position: center;
            height: 100vh;
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;    
            display: flex;
            align-items: center;
            justify-content: center; 
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
        }

        label {
            display: block;
            margin-bottom: 8px;
        }

        input {
            width: 100%;
            padding: 8px;
            margin-bottom: 12px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }
    </style>
</head>
<body>
    <h2>ลงทะเบียน</h2>
    <form method="post">
        {% csrf_token %}
        
        <div>
            <label for="id_username">Username:</label><br>
            {{ form.username }}
            {% for error in form.username.errors %}
                <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
        </div>
        
        <div>
            <label for="id_email">Email:</label><br>
            {{ form.email }}
            {% for error in form.email.errors %}
                <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
        </div>
        
        <div>
            <label for="id_password1">Password:</label><br>
            {{ form.password1 }}
            {% for error in form.password1.errors %}
                <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
        </div>
        
        <div>
            <label for="id_password2">Password confirmation:</label><br>
            {{ form.password2 }}
            {% for error in form.password2.errors %}
                <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
        </div>
        
        <button type="submit">Register</button>
    </form>
</body>
</html>